### ISSUE TITLE
How to restore backgroundView on Refresh Page

### ISSUE THREAD

**Issue by Creo-KR** [serkodev/nuxt-pages-plus#8]
Hi, I am using Nuxt3.
I have a problem using this module.
First, open the modal through`<PlusModalLink to="/any-path/any-id" />`.
And how do I restore the previous page when I refresh browser?

```
app.vue
<template>
        <NuxtLayout>
            <PlusModalNuxtPage />
        </NuxtLayout>

        <PlusModalPage name="dialog" />
</template
```
make open modal Page path: `/pages/open-dialog.vue`
Dialog path: `/pages/any-path/[id]@dialog.vue`
and another page [for preventing page not found] path : `/pages/any-path/[[id]].vue`

I found `history.state.backgroundView === '/pages/open-dialog'`.
So when I refresh the browser, I want to restore the previous page to the `/pages/open-dialog' path.
Then open the previously opened modal.

**Comment by serkodev** [comment]
This is the expected behavior. The page `/pages/any-path/[[id]]` is not designed to prevent 'page not found' errors.

If you need `history.state.backgroundView` to serve as the background view for your modal, you may need to implement it yourself in `/pages/any-path/[[id]].vue` by reading `history.state.backgroundView` and rendering the appropriate 'background' component.
